name: ccc
mode: dev
version: 1.0.0

mysql:
  address: localhost:3306
  name: test
  user: root
  password: 123

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0

miniprogram:
  appid:
  secret:
  mchid:
  certSerialNo:
  apiV3Key:
  certPath:
  keyPath:

log:
  path: ./logs # 日志文件目录
  logFileName: gin.log # 日志文件名
  stdout: true # 是否输出到控制台
  level: debug # 最低记录级别
  zap:
    outFormat: json # json/
  lumberJack: # 日志文件切割和压缩
    maxSize: 1 # 单文件最大容量(单位MB)
    maxBackups: 3 # 保留旧文件的最大数量
    maxAge: 30 # 旧文件最多保存几天
    compress: false #是否压缩/归档旧文件